name: "haiku-ci"
on: [push, pull_request, workflow_dispatch]

jobs:
  build-haiku:
    timeout-minutes: 60
    runs-on: ${{ matrix.config.runner }}
    name: build-${{ matrix.config.os }}-${{ matrix.config.version }}-${{ matrix.config.architecture }}

    strategy:
      fail-fast: false
      matrix:
        config:
          # The OS versions supported are specific to the version of the action
          # https://github.com/cross-platform-actions/action/blob/master/changelog.md
          - { os: haiku, version: 'r1beta4', runner: 'ubuntu-latest', architecture: 'x86-64' }
          - { os: haiku, version: 'r1beta4',  runner: 'ubuntu-latest', architecture: 'x86' }

    steps:
      - uses: actions/checkout@v4

      - uses: korli/action@v0.23.0-haiku
        with:
          operating_system: ${{ matrix.config.os }}
          version: ${{ matrix.config.version }}
          architecture: ${{ matrix.config.architecture }}
          run: |
            ssh user@localhost "chmod 777 /tmp/; pkgman update -y cmd:perl cmd:make" &&
            if [[ `uname -m` == BePC ]]; then
              ssh user@localhost "pkgman update -y cmd:gcc_x86 cmd:as_x86 cmd:pkg_config_x86 gcc_x86_syslibs_devel devel:libz_x86" &&
              setarch x86 bash -c "./config zlib shared no-asm -g && make && make test"
            else
              ssh user@localhost "pkgman update -y cmd:gcc cmd:as cmd:pkg_config gcc_syslibs_devel devel:libz" &&
              ./config zlib shared no-asm -g &&
              make && make test
            fi
